# Gitlab Continuous Integration for yex
#
# see https://medium.com/cubemail88/setting-gitlab-ci-cd-for-python-application-b59f1fb70efe for ideaidea

image: "python:3.9"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - test

pytest:
  stage: test
  script:
    - python -m pytest
